/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedPurchaseRequestsIndexRouteImport } from './routes/_authenticated/purchase-requests.index'
import { Route as AuthenticatedPurchaseRequestsIdRouteImport } from './routes/_authenticated/purchase-requests.$id'
import { Route as AuthenticatedSubstitutionsIndexRouteImport } from './routes/_authenticated/substitutions.index'
import { Route as AuthenticatedSubstitutionsIdRouteImport } from './routes/_authenticated/substitutions.$id'
import { Route as AuthenticatedTransfersIndexRouteImport } from './routes/_authenticated/transfers.index'
import { Route as AuthenticatedTransfersIdRouteImport } from './routes/_authenticated/transfers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseRequestsIndexRoute =
  AuthenticatedPurchaseRequestsIndexRouteImport.update({
    id: '/purchase-requests/',
    path: '/purchase-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseRequestsIdRoute =
  AuthenticatedPurchaseRequestsIdRouteImport.update({
    id: '/purchase-requests/$id',
    path: '/purchase-requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubstitutionsIndexRoute =
  AuthenticatedSubstitutionsIndexRouteImport.update({
    id: '/substitutions/',
    path: '/substitutions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubstitutionsIdRoute =
  AuthenticatedSubstitutionsIdRouteImport.update({
    id: '/substitutions/$id',
    path: '/substitutions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransfersIndexRoute =
  AuthenticatedTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransfersIdRoute =
  AuthenticatedTransfersIdRouteImport.update({
    id: '/transfers/$id',
    path: '/transfers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/purchase-requests/$id': typeof AuthenticatedPurchaseRequestsIdRoute
  '/substitutions/$id': typeof AuthenticatedSubstitutionsIdRoute
  '/transfers/$id': typeof AuthenticatedTransfersIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/purchase-requests/': typeof AuthenticatedPurchaseRequestsIndexRoute
  '/substitutions/': typeof AuthenticatedSubstitutionsIndexRoute
  '/transfers/': typeof AuthenticatedTransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/purchase-requests/$id': typeof AuthenticatedPurchaseRequestsIdRoute
  '/substitutions/$id': typeof AuthenticatedSubstitutionsIdRoute
  '/transfers/$id': typeof AuthenticatedTransfersIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/purchase-requests': typeof AuthenticatedPurchaseRequestsIndexRoute
  '/substitutions': typeof AuthenticatedSubstitutionsIndexRoute
  '/transfers': typeof AuthenticatedTransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/purchase-requests/$id': typeof AuthenticatedPurchaseRequestsIdRoute
  '/_authenticated/substitutions/$id': typeof AuthenticatedSubstitutionsIdRoute
  '/_authenticated/transfers/$id': typeof AuthenticatedTransfersIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/purchase-requests/': typeof AuthenticatedPurchaseRequestsIndexRoute
  '/_authenticated/substitutions/': typeof AuthenticatedSubstitutionsIndexRoute
  '/_authenticated/transfers/': typeof AuthenticatedTransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/team'
    | '/projects/$id'
    | '/purchase-requests/$id'
    | '/substitutions/$id'
    | '/transfers/$id'
    | '/projects/'
    | '/purchase-requests/'
    | '/substitutions/'
    | '/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/team'
    | '/projects/$id'
    | '/purchase-requests/$id'
    | '/substitutions/$id'
    | '/transfers/$id'
    | '/projects'
    | '/purchase-requests'
    | '/substitutions'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/projects/$id'
    | '/_authenticated/purchase-requests/$id'
    | '/_authenticated/substitutions/$id'
    | '/_authenticated/transfers/$id'
    | '/_authenticated/projects/'
    | '/_authenticated/purchase-requests/'
    | '/_authenticated/substitutions/'
    | '/_authenticated/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-requests/': {
      id: '/_authenticated/purchase-requests/'
      path: '/purchase-requests'
      fullPath: '/purchase-requests/'
      preLoaderRoute: typeof AuthenticatedPurchaseRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-requests/$id': {
      id: '/_authenticated/purchase-requests/$id'
      path: '/purchase-requests/$id'
      fullPath: '/purchase-requests/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/substitutions/': {
      id: '/_authenticated/substitutions/'
      path: '/substitutions'
      fullPath: '/substitutions/'
      preLoaderRoute: typeof AuthenticatedSubstitutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/substitutions/$id': {
      id: '/_authenticated/substitutions/$id'
      path: '/substitutions/$id'
      fullPath: '/substitutions/$id'
      preLoaderRoute: typeof AuthenticatedSubstitutionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers/': {
      id: '/_authenticated/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AuthenticatedTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers/$id': {
      id: '/_authenticated/transfers/$id'
      path: '/transfers/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof AuthenticatedTransfersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedPurchaseRequestsIdRoute: typeof AuthenticatedPurchaseRequestsIdRoute
  AuthenticatedSubstitutionsIdRoute: typeof AuthenticatedSubstitutionsIdRoute
  AuthenticatedTransfersIdRoute: typeof AuthenticatedTransfersIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedPurchaseRequestsIndexRoute: typeof AuthenticatedPurchaseRequestsIndexRoute
  AuthenticatedSubstitutionsIndexRoute: typeof AuthenticatedSubstitutionsIndexRoute
  AuthenticatedTransfersIndexRoute: typeof AuthenticatedTransfersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedPurchaseRequestsIdRoute: AuthenticatedPurchaseRequestsIdRoute,
  AuthenticatedSubstitutionsIdRoute: AuthenticatedSubstitutionsIdRoute,
  AuthenticatedTransfersIdRoute: AuthenticatedTransfersIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedPurchaseRequestsIndexRoute:
    AuthenticatedPurchaseRequestsIndexRoute,
  AuthenticatedSubstitutionsIndexRoute: AuthenticatedSubstitutionsIndexRoute,
  AuthenticatedTransfersIndexRoute: AuthenticatedTransfersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
